GOLANGCI_LINT_VERSION := v2.1.6

install-linter:
    @echo "🔧 Установка golangci-lint {{GOLANGCI_LINT_VERSION}}..."
    {{GO}} install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{GOLANGCI_LINT_VERSION}}
